version: '3.1'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
