-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	username VARCHAR(20) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);
-- CREATE TABLE IF NOT EXISTS sections (
--   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   head VARCHAR(255) DEFAULT NULL,
--   image_id uuid NOT NULL,
--   created_at TIMESTAMP,
--   updated_at TIMESTAMP
-- );
-- CREATE TABLE IF NOT EXISTS posts (
--   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   head VARCHAR(255) NOT NULL,
--   body TEXT DEFAULT NULL,
--   image_id uuid NOT NULL,
--   section_id INTEGER REFERENCES sections(id) ON DELETE CASCADE,
--   user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
--   created_at TIMESTAMP,
--   updated_at TIMESTAMP
-- );
-- CREATE TABLE IF NOT EXISTS comments (
--   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   body TEXT NOT NULL,
--   post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
--   user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
--   created_at TIMESTAMP,
--   updated_at TIMESTAMP
-- );

